name : Checkov Scan
appendCommitMessageToRunName: false
trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Install checkov'
  inputs:
    targetType: 'inline'
    script: 'pip3 install checkov'
    
- task: Bash@3
  displayName: 'Checkov Static Code Analysis'
  inputs:
    targetType: 'inline'
    script: |
       mkdir checkov-report
       checkov -d . --skip-path ./*.json --output junitxml > $(System.DefaultWorkingDirectory)/checkov-report/TEST-checkov-report.xml
- task: PublishTestResults@2
  displayName: 'Publish checkov Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/checkov-report'
    testRunTitle: 'checkov'
